POST http://localhost:8080/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIzMzIxNDMyLCJ1c2VyaWQiOjJ9.HsyRhsK0agpmNXSraE_GYKygy8rDfBjwDxruSwS0x8w